---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/pivotal-kahin-ng/TnC.git
    branch: ci

jobs:
- name: unit-tests
  public: true
  serial: true
  plan:  
  - get: repo
    trigger: true
  - task: run-tests
    file: repo/Concourse/run-test.yml

- name: deploy
  plan:
  - get: repo
  passed: [unit-tests]
  - task: deploy
    config:
      platform: darwin
      inputs:
        - name: repo
      run:
        path: bash
        args:
          - -exc
          - |
            fastlane build