---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/pivotal-kahin-ng/TnC.git
    branch: ci

jobs:
- name: unit-test
  public: true
  serial: true
  plan:  
  - get: repo
    trigger: true
  - task: run-tests
    config: 
      platform: darwin
      inputs:
         - name: repo
      run:
        path: bash
        args:
          - "-c"
          - "cd repo && export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin && bundle install && bundle exec fastlane bootstrap_dependencies && bundle exec fastlane test"

- name: deploy
  plan: 
  - get: repo
    trigger: true
    passed: [unit-test]
  - task: make-ipa
    config: 
      platform: darwin
      inputs:
         - name: repo
      run:
        path: bash
        args:
          - "-c"
          - "cd repo && export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin && bundle install && bundle exec fastlane build"