---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/pivotal-kahin-ng/TnC.git
    branch: ci

jobs:
- name: unit-test
  public: true
  serial: true
  plan:  
  - get: repo
    trigger: true
  - task: run-tests
    path: bash
    args:
      - "-c"
      - "cd repo && fastlane bootstrap_dependencies && fastlane test"

- name: deploy
  plan: 
  - get: repo
    trigger: true
    passed: [unit-test]
  - task: make-ipa
    path: bash
    args:
      - "-c"
      - "cd repo && fastlane build"