language: objective-c
osx_image: xcode8
xcode_workspace: YelpAPI.xcworkspace
xcode_scheme: YelpAPI
xcode_sdk: iphonesimulator
script: set -o pipefail && xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -destination 'name=iPhone 6' build test | xcpretty
